### ISSUE TITLE
collect data for all minecraft release version

### ISSUE THREAD

**Issue by fnaith** [Articdive/ArticData#5]
Would you consider to collect data for all release version ?

minecraft version : https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by Articdive** [comment]
I've added 1.18.2 to the list of supported data.
Due to some pretty big changes between 1.16.2 and 1.16.3 the amount of work to get data for versions prior to 1.16.3 is a lot. This framework would allow you to easily do so however, you could look at how 1.16.5 and 1.17 are handled and simply handle 1.16.2, just the generators would look completely different because the codebase significally changed in those versions (between 1.16.2 and 1.16.3). Due to a lack of time and because most people don't write anything for versions before 1.16, I don't see the dedication as worth it, others may do so and should feel free to contribute.

**Comment by fnaith** [comment]
I just curious about how many version will this project support and didn't know 1.16 change so many thing.
Thanks you for sharing this knowledge.
Great job !
