### ISSUE TITLE
PotionEffects are missing modifiers

### ISSUE THREAD

**Issue by DietrichPaul** [Articdive/ArticData#8]
Example

```json
"speed": {
    "id": 1,
    "color": 1234,
    "instantaneous": false,
    "translationKey": "peter123"
    "mojangName": "SPEED",
    "modifiers": [
      {
        "attribute": "GENERIC_MOVEMENT_SPEED",
        "uuid": "91aeaa56-376b-4498-935b-2f7f68070635",
        "value": 0.20000000298023224,
        "operation": "MULTIPLY_TOTAL"
      }
    ]
  }
```

**Comment by Articdive** [comment]
Added in https://github.com/Articdive/ArticDataGenerator/commit/6e64490656fe0e696ec3cc192cdb808e925a1743

Please note that strength and weakness (maybe some more) have a value of 0.0, since they are handled differentely in the minecraft code, it's not a mistake, it's the genuine way it's implemented, strength does not change the damage attribute for whatever reason. 🤷🏼
